### ISSUE TITLE
[NON-ISSUE] Add speech pack downloads URL

### ISSUE THREAD

**Issue by e3ndr** [depau/SAPISpeechServer#2]
Would you kindly add this link to the "add more voices" section of the README? I think it would be useful for most people :)

https://www.microsoft.com/en-us/download/details.aspx?id=27224

**Comment by depau** [comment]
Hi! Thanks for your suggestions, that does sound useful but have you tested that they work? The page seems to refer to SAPI version 11 but this project uses SAPI v5.

I'll see if I can test those voices later this week.

**Comment by e3ndr** [comment]
🤦‍♂️ Yeah just tried it, doesn't work. So nevermind :P


Any interest in updating this project to support 11?

**Comment by depau** [comment]
The goal is for this to run on Linux via Wine. I'm not aware of ways to install the SAPI 11 libraries on Wine. As far as I understand, unlike SAPI 5 which comes in a convenient installer, SAPI 11 is bundled with Windows.

So unfortunately I'm not planning to add support for SAPI 11 unless we can also support it on Wine.
